#!/bin/sh
mxmlc \
  -static-link-runtime-shared-libraries \
  -compiler.debug \
	-incremental \
  $1.as && \
mv $1.swf naubino.swf && \
flashplayer-debugger-standalone naubino.swf
#firefox naubino.swf
